version: "3.7"
services:
    qt:
        container_name: qt
        image: "pco-qt:2020"
        build:
            context: .
            args: 
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
        volumes:
            - "$HOME/.Xauthority:/home/user/.Xauthority"
            - "/tmp/.X11-unix:/tmp/.X11-unix"
            - "qt-bin:/home/user/Qt"
            - "qt-conf:/home/user/.config/QtProject"
            - "./projects:/home/user/projects"
        environment:
            - DISPLAY=$DISPLAY
        network_mode: "host"
volumes:
    qt-bin:
    qt-conf:
